export { default as pluginTypescript } from '@typescript-eslint/eslint-plugin'
export * as parserTypescript from '@typescript-eslint/parser'
export * as pluginImport from 'eslint-plugin-i'
export { default as pluginJest } from 'eslint-plugin-jest'
export { default as pluginJSDoc } from 'eslint-plugin-jsdoc'
export { default as pluginJSONFiles } from 'eslint-plugin-json-files'
export * as pluginJSON from 'eslint-plugin-jsonc'
export { default as pluginJsxA11y } from 'eslint-plugin-jsx-a11y'
export { default as pluginNode } from 'eslint-plugin-n'
export { default as pluginPerfectionist } from 'eslint-plugin-perfectionist'
export { default as pluginPrettier } from 'eslint-plugin-prettier'
export { default as pluginPromise } from 'eslint-plugin-promise'
export { default as pluginReact } from 'eslint-plugin-react'
export { default as pluginReactHooks } from 'eslint-plugin-react-hooks'
export { default as pluginTailwindcss } from 'eslint-plugin-tailwindcss'
export { default as pluginUnicorn } from 'eslint-plugin-unicorn'
export * as parserJSON from 'jsonc-eslint-parser'
export { default as tseslint } from 'typescript-eslint'
